// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mprpcHeader.proto

#include "mprpcHeader.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace mprpcHeader {
PROTOBUF_CONSTEXPR rpcHeader::rpcHeader(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.servicename_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.methodname_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.argssize_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct rpcHeaderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR rpcHeaderDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~rpcHeaderDefaultTypeInternal() {}
  union {
    rpcHeader _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 rpcHeaderDefaultTypeInternal _rpcHeader_default_instance_;
}  // namespace mprpcHeader
static ::_pb::Metadata file_level_metadata_mprpcHeader_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_mprpcHeader_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_mprpcHeader_2eproto = nullptr;

const uint32_t TableStruct_mprpcHeader_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mprpcHeader::rpcHeader, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mprpcHeader::rpcHeader, _impl_.servicename_),
  PROTOBUF_FIELD_OFFSET(::mprpcHeader::rpcHeader, _impl_.methodname_),
  PROTOBUF_FIELD_OFFSET(::mprpcHeader::rpcHeader, _impl_.argssize_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::mprpcHeader::rpcHeader)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::mprpcHeader::_rpcHeader_default_instance_._instance,
};

const char descriptor_table_protodef_mprpcHeader_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021mprpcHeader.proto\022\013mprpcHeader\"F\n\trpcH"
  "eader\022\023\n\013serviceName\030\001 \001(\t\022\022\n\nmethodName"
  "\030\002 \001(\t\022\020\n\010argsSize\030\003 \001(\rb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_mprpcHeader_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_mprpcHeader_2eproto = {
    false, false, 112, descriptor_table_protodef_mprpcHeader_2eproto,
    "mprpcHeader.proto",
    &descriptor_table_mprpcHeader_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_mprpcHeader_2eproto::offsets,
    file_level_metadata_mprpcHeader_2eproto, file_level_enum_descriptors_mprpcHeader_2eproto,
    file_level_service_descriptors_mprpcHeader_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_mprpcHeader_2eproto_getter() {
  return &descriptor_table_mprpcHeader_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_mprpcHeader_2eproto(&descriptor_table_mprpcHeader_2eproto);
namespace mprpcHeader {

// ===================================================================

class rpcHeader::_Internal {
 public:
};

rpcHeader::rpcHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mprpcHeader.rpcHeader)
}
rpcHeader::rpcHeader(const rpcHeader& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  rpcHeader* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.servicename_){}
    , decltype(_impl_.methodname_){}
    , decltype(_impl_.argssize_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.servicename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.servicename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_servicename().empty()) {
    _this->_impl_.servicename_.Set(from._internal_servicename(), 
      _this->GetArenaForAllocation());
  }
  _impl_.methodname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.methodname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_methodname().empty()) {
    _this->_impl_.methodname_.Set(from._internal_methodname(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.argssize_ = from._impl_.argssize_;
  // @@protoc_insertion_point(copy_constructor:mprpcHeader.rpcHeader)
}

inline void rpcHeader::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.servicename_){}
    , decltype(_impl_.methodname_){}
    , decltype(_impl_.argssize_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.servicename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.servicename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.methodname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.methodname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

rpcHeader::~rpcHeader() {
  // @@protoc_insertion_point(destructor:mprpcHeader.rpcHeader)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void rpcHeader::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.servicename_.Destroy();
  _impl_.methodname_.Destroy();
}

void rpcHeader::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void rpcHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:mprpcHeader.rpcHeader)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.servicename_.ClearToEmpty();
  _impl_.methodname_.ClearToEmpty();
  _impl_.argssize_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* rpcHeader::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string serviceName = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_servicename();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mprpcHeader.rpcHeader.serviceName"));
        } else
          goto handle_unusual;
        continue;
      // string methodName = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_methodname();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mprpcHeader.rpcHeader.methodName"));
        } else
          goto handle_unusual;
        continue;
      // uint32 argsSize = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.argssize_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* rpcHeader::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mprpcHeader.rpcHeader)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string serviceName = 1;
  if (!this->_internal_servicename().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_servicename().data(), static_cast<int>(this->_internal_servicename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mprpcHeader.rpcHeader.serviceName");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_servicename(), target);
  }

  // string methodName = 2;
  if (!this->_internal_methodname().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_methodname().data(), static_cast<int>(this->_internal_methodname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mprpcHeader.rpcHeader.methodName");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_methodname(), target);
  }

  // uint32 argsSize = 3;
  if (this->_internal_argssize() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_argssize(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mprpcHeader.rpcHeader)
  return target;
}

size_t rpcHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mprpcHeader.rpcHeader)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string serviceName = 1;
  if (!this->_internal_servicename().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_servicename());
  }

  // string methodName = 2;
  if (!this->_internal_methodname().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_methodname());
  }

  // uint32 argsSize = 3;
  if (this->_internal_argssize() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_argssize());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData rpcHeader::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    rpcHeader::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*rpcHeader::GetClassData() const { return &_class_data_; }


void rpcHeader::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<rpcHeader*>(&to_msg);
  auto& from = static_cast<const rpcHeader&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mprpcHeader.rpcHeader)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_servicename().empty()) {
    _this->_internal_set_servicename(from._internal_servicename());
  }
  if (!from._internal_methodname().empty()) {
    _this->_internal_set_methodname(from._internal_methodname());
  }
  if (from._internal_argssize() != 0) {
    _this->_internal_set_argssize(from._internal_argssize());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void rpcHeader::CopyFrom(const rpcHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mprpcHeader.rpcHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool rpcHeader::IsInitialized() const {
  return true;
}

void rpcHeader::InternalSwap(rpcHeader* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.servicename_, lhs_arena,
      &other->_impl_.servicename_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.methodname_, lhs_arena,
      &other->_impl_.methodname_, rhs_arena
  );
  swap(_impl_.argssize_, other->_impl_.argssize_);
}

::PROTOBUF_NAMESPACE_ID::Metadata rpcHeader::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mprpcHeader_2eproto_getter, &descriptor_table_mprpcHeader_2eproto_once,
      file_level_metadata_mprpcHeader_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace mprpcHeader
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mprpcHeader::rpcHeader*
Arena::CreateMaybeMessage< ::mprpcHeader::rpcHeader >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mprpcHeader::rpcHeader >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
